//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_MVC.FromWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FromWCF.IBibliotecaService")]
    public interface IBibliotecaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/GetBooks", ReplyAction="http://tempuri.org/IBibliotecaService/GetBooksResponse")]
        System.Collections.Generic.List<EntityModels.BookAuthors> GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/GetBooks", ReplyAction="http://tempuri.org/IBibliotecaService/GetBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntityModels.BookAuthors>> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/InsertBook", ReplyAction="http://tempuri.org/IBibliotecaService/InsertBookResponse")]
        EntityModels.Book InsertBook(EntityModels.Book b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBibliotecaService/InsertBook", ReplyAction="http://tempuri.org/IBibliotecaService/InsertBookResponse")]
        System.Threading.Tasks.Task<EntityModels.Book> InsertBookAsync(EntityModels.Book b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBibliotecaServiceChannel : Form_MVC.FromWCF.IBibliotecaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BibliotecaServiceClient : System.ServiceModel.ClientBase<Form_MVC.FromWCF.IBibliotecaService>, Form_MVC.FromWCF.IBibliotecaService {
        
        public BibliotecaServiceClient() {
        }
        
        public BibliotecaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BibliotecaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EntityModels.BookAuthors> GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntityModels.BookAuthors>> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public EntityModels.Book InsertBook(EntityModels.Book b) {
            return base.Channel.InsertBook(b);
        }
        
        public System.Threading.Tasks.Task<EntityModels.Book> InsertBookAsync(EntityModels.Book b) {
            return base.Channel.InsertBookAsync(b);
        }
    }
}
