// <auto-generated />
namespace From_WCF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class view_BookAuthors_V2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(view_BookAuthors_V2));
        
        string IMigrationMetadata.Id
        {
            get { return "201502201511143_view_BookAuthors_V2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
